### ISSUE TITLE
Run button does not work 1st time

### ISSUE THREAD

**Issue by wintvelt** [alpacaaa/runelm.io#3]
The Run-button doesn't do anything the first time it is clicked.
You need to do CTRL-S (windows) or Command-S (mac) first. After that, the button works..

To reproduce
- go to https://runelm.io/new
- change something in the code
- click Run
Nothing happens

Better would be if the button works also the first time :wink:

**Comment by mikeLspohn** [comment]
This was working fine for me before, but today clicking the run button from just the standard new template doesn't do anything no matter how many times I click it. Also, it seems like the section to add dependencies is now missing. Did something change?

I'm on osx Sierra using Chrome.

**Comment by mikeLspohn** [comment]
Ahhh, so after doing the `ctrl-s` it worked, and I see the settings again, so disregard that. The button click issue is still kinda wonky though 😄

**Comment by alpacaaa** [comment]
@wintvelt sorry for the delay! This is now fixed, thanks a lot for reporting!! 😄
